version: "3.5"

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword